### ISSUE TITLE
BarkodVeriSil

### ISSUE THREAD

**Issue by harslannet** [ahmeti/ptt-kargo-api#1]
Selamlar, 

BarkodVeriSil endpoint'ine istek yaptığımda dönen veri her zaman şu şekilde oluyor;

` <ax21:aciklama>Silme loglama islemi yapilamadi.islem basarisiz</ax21:aciklama>`
 `<ax21:hataKodu>-1</ax21:hataKodu>`

Sizde `PttBarkodVeriSil()` metodundaki if koşulunda `if( is_array($result) && $result['hataKodu'] == 1 )` şunu kullanmışsınız ve sonuc true demişsiniz, hataKodu 1 tamam ama açıklama mesajı işlem başarısız olarak dönüyor. Bu konuda tecrübeniz varsa bilgi verebilir misiniz ? Açıklama bu olmasına rağmen iptal edebilmiş mi oluyorum yani? 

Düzenleme: Pardon bende dönen hata kodu -1 ya! :) dikkatsizlik. Ama iptal etme işlemini bir türlü başaramadım her aşamadaki pakette denedim ama hep bu sonucu alıyorum!

**Comment by ahmeti** [comment]
Merhaba @harslannet,

Açıkçası uzun zamandır API'yi kullanmadım. Fakat kullanan kişiler şöyle bir geri bildirimde bulundu. 

BarkodVeriSil metodu ile sadece API üzerinden oluşturulan barkodlar silinebiliyormuş.

Aldığın hata ile ilgili aklıma iki soru geliyor;

1. Silmek istediğiniz barkodu API ile mi oluşturdunuz?

2. Barkodu oluştururken kaydettiğiniz **DosyaAdi** değerini doğru bir şekilde gönderiyor musunuz?

İyi çalışmalar.

**Comment by harslannet** [comment]
Selamlar, 
PTT kargo bize n adet barkod verdi ve kullandığımız alt yapı o barkod listesinden sırayla API ile PTT kargoya gönderiyor isteği. Alt yapı kapalı sistem olduğu için açıkçası DosyaAdi bilgisini gönderiyor mu bilmiyorum. 

Zaten ben BarkodVeriSil 'e istek atarken DosyaAdi bilgisini boş gönderiyorum (bu şekilde de kabul ettiğini düşündüğüm için etmiyorsa sorun orada zaten!)

**Comment by ahmeti** [comment]
Maalesef BarkodVeriSil için DosyaAdi bilgisini göndermek zorundasınız.
